#사용할 변수
varialbles:
  # 백엔드가 동작할 포트
  port: 9000

#여기서부터 설정파일
server:
  port: ${varialbles.port}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eagerbeaver?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    username: root
    password: ssafy
  jpa:
    hibernate:
      ddl-auto: create-drop
    show_sql: true
    properties:
      hibernate:
        format_sql: true #쿼리 포맷팅 활성화

logging.level:
  org.hibernate.SQL: info


