spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://j9a507.p.ssafy.io:3426/eagerbeaver
    username: root
    password: kbsw2jEB!
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true
        show_sql: true

    defer-datasource-initialization: true   #-> data.sql을 사용하기 위해 추가

  redis:
    redishost: localhost
    redisport: 4805
    redisPassword: EBroot
logging:
  level:
    com.ground.sswm : INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO

