#여기서부터 설정파일
server:
  servlet:
    context-path: /api
  port:
    9000

spring:
  profiles:
    default: local

#springdoc:
#  api-docs:
#    packages:
#      base: ssafy.eagerbeaver.controller

#springfox:
#  documentation:
#    enabled: true

## swagger
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#    groups-order: DESC
#    operationsSorter: method
#    disable-swagger-default-url: true
#    display-request-duration: true
#    api-docs:
#      path: /api-docs
#    show-actuator: true
#    default-consumes-media-type: application/json
#    default-produces-media-type: application/json
#    paths-to-match:
#      - /v1/**