spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/eagerbeaver
    username: EB
    password: kbsw2jEB!
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
#        show_sql: true
  redis:
    host: localhost
    port: 4805
    password: EBroot

logging:
  level:
    com.ground.sswm : DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  servlet:
    context-path: /api
  port:
    8080

# kakao 관련
kakao:
  rest-api-key: 7ea82d8a610fe51bcf3eca267069b264 # 이전 플젝꺼 임시로 가져옴
  redirect-uri: http://localhost:9000/api/auth/login # 프론트 연결 시 url은 다름

# 자체 jwt 관련
jwt:
  secret: eagerbeaversecretkeyhihellochillout